engines:
  rubocop:
    enabled: true
  eslint:
    enabled: true
  duplication:
    exclude_paths:
      - test/
    enabled: true
    checks:
      Similar code:
        enabled: false
    config:
      languages:
        - javascript
exclude_paths:
- build/**/*
- coverage/**/*

